version: "2"
services: 
  app:
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SERVER="${SERVER}"

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
      - 9006:9006
    depends_on:
      - app

  